name: Deploy to EC2

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Push Docker Image with Jib
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKER_EMAIL }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          mvn compile jib:build \
            -Dimage=louislu000/jobs-microservice:latest \
            -Djib.to.auth.username=$REGISTRY_USERNAME \
            -Djib.to.auth.password=$REGISTRY_PASSWORD

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

#      - name: Deploy to EC2
#        env:
#          EC2_HOST: ${{ secrets.EC2_HOST }}
#          CONTAINER_IMAGE: louislu000/jobs-microservice:latest
#        run: |
#          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_HOST << 'EOF'
#            docker pull $CONTAINER_IMAGE
#            docker stop my-spring-app || true
#            docker rm my-spring-app || true
#            docker run -d --name my-spring-app -p 8080:8080 \
#              -e DB_URL=$DB_URL \
#              -e DB_USERNAME=$DB_USERNAME \
#              -e DB_PASSWORD=$DB_PASSWORD \
#              $CONTAINER_IMAGE
#          EOF
